# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='Mobile Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('time_stamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
