# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180314_1902'),
        ('customer', '0002_auto_20180314_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False, verbose_name='Order ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, verbose_name='Quantity')),
                ('order_cost', models.IntegerField(blank=True, verbose_name='Order Cost')),
                ('status', models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Received'), ('2', 'Dispatched'), ('3', 'Delivered'), ('4', 'Cancelled'), ('5', 'Cancelled by Vendor')], default='0', max_length=1, verbose_name='Status of Order')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='product.Item')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
