# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
