# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180318_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.CASCADE, to='product.Item'),
        ),
    ]
