# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20180318_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
