# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(db_column='brand_id', primary_key=True, serialize=False, verbose_name='Company ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='Company Name')),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(db_column='item_id', primary_key=True, serialize=False, verbose_name='Item ID ')),
                ('item_name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('item_cost', models.IntegerField(verbose_name='Item Cost')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='product_id', primary_key=True, serialize=False, verbose_name='Product ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('offers', models.TextField(blank=True, verbose_name='Offers')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('additional_info', models.TextField(blank=True, verbose_name='Additional Info')),
                ('brand', models.ForeignKey(db_column='brand', on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
