# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_cost',
            field=models.PositiveSmallIntegerField(verbose_name='Item Cost'),
        ),
    ]
