# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180314_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.AutoField(db_column='brand_id', primary_key=True, serialize=False, verbose_name='Brand ID'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=50, verbose_name='Brand Name'),
        ),
    ]
